name: Deploy Dist to Deploy Branch

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout del repositorio
    - name: Checkout repository
      uses: actions/checkout@v3

    # Elimina la carpeta dist si existe
    - name: Remove dist folder
      run: rm -rf dist

    # Construye el proyecto para generar la carpeta dist
    - name: Build project
      run: npm install && npm run build

    # Configura Git
    - name: Configure Git
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    # Inicializa la carpeta deploy (siempre sobreescribe)
    - name: Deploy to deploy branch
      run: |
        git fetch origin deploy || echo "Deploy branch doesn't exist"
        git checkout -B deploy
        rm -rf ./*
        cp -r dist/* ./
        git add .
        git commit -m "Deploy from GitHub Actions" || echo "No changes to commit"
        git push origin deploy --force
