name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Force change in dist
        run: echo "force update" > dist/.force-update

      - name: Deploy dist folder to deploy branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Deploy from GitHub Actions"
          git push origin `git subtree split --prefix dist main`:deploy --force
