name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el c贸digo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configurar la versi贸n de Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20  # Ajusta a la versi贸n compatible

      # 3. Instalar dependencias y construir el proyecto
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. Dar permisos de ejecuci贸n al script deploy.sh
      - name: Make deploy script executable
        run: chmod +x deploy.sh

      # 5. Ejecutar el script deploy.sh
      - name: Execute deploy script
        run: ./deploy.sh
