name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout el código
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Configuración del token y despliegue
      - name: Deploy dist folder
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add dist
          git commit -m "Deploy from GitHub Actions"
          git push origin `git subtree split --prefix dist main`:deploy --force
